// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package bowls

import (
	"database/sql"
)

type Bowl struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}
