// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1, arg2) {
  return window['go']['bowls']['BowelService']['Create'](arg1, arg2);
}

export function DeleteById(arg1) {
  return window['go']['bowls']['BowelService']['DeleteById'](arg1);
}

export function GetAll() {
  return window['go']['bowls']['BowelService']['GetAll']();
}

export function GetById(arg1) {
  return window['go']['bowls']['BowelService']['GetById'](arg1);
}

export function UpdateById(arg1, arg2) {
  return window['go']['bowls']['BowelService']['UpdateById'](arg1, arg2);
}
