// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bowls} from '../models';

export function Create(arg1:string,arg2:any):Promise<bowls.Bowl>;

export function DeleteById(arg1:number):Promise<void>;

export function GetAll():Promise<Array<bowls.Bowl>>;

export function GetById(arg1:number):Promise<bowls.Bowl>;

export function UpdateById(arg1:number,arg2:bowls.BowlUpdate):Promise<bowls.Bowl>;
