// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1, arg2, arg3) {
  return window['go']['flakes']['FlakesService']['Create'](arg1, arg2, arg3);
}

export function DeleteById(arg1) {
  return window['go']['flakes']['FlakesService']['DeleteById'](arg1);
}

export function GetAll() {
  return window['go']['flakes']['FlakesService']['GetAll']();
}

export function GetAllByBowlId(arg1) {
  return window['go']['flakes']['FlakesService']['GetAllByBowlId'](arg1);
}

export function GetById(arg1) {
  return window['go']['flakes']['FlakesService']['GetById'](arg1);
}
