// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1, arg2, arg3) {
  return window['go']['flakes']['FlakeService']['Create'](arg1, arg2, arg3);
}

export function DeleteById(arg1, arg2) {
  return window['go']['flakes']['FlakeService']['DeleteById'](arg1, arg2);
}

export function GetAll() {
  return window['go']['flakes']['FlakeService']['GetAll']();
}

export function GetAllByBowlId(arg1) {
  return window['go']['flakes']['FlakeService']['GetAllByBowlId'](arg1);
}

export function GetById(arg1) {
  return window['go']['flakes']['FlakeService']['GetById'](arg1);
}

export function UpdateById(arg1, arg2) {
  return window['go']['flakes']['FlakeService']['UpdateById'](arg1, arg2);
}
