// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package flakes

type Flake struct {
	ID          int64   `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	BowlID      int64   `json:"bowlId"`
}
