// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package todos

import (
	"time"
)

type Flake struct {
	ID          int64   `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	BowlID      int64   `json:"bowlId"`
}

type Todo struct {
	ID          int64     `json:"id"`
	FlakeID     int64     `json:"flakeId"`
	Done        int64     `json:"done"`
	ScheduledAt time.Time `json:"scheduledAt"`
}
