// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1, arg2) {
  return window['go']['todos']['TodosService']['Create'](arg1, arg2);
}

export function GetAll() {
  return window['go']['todos']['TodosService']['GetAll']();
}

export function GetAllByFlakeId(arg1) {
  return window['go']['todos']['TodosService']['GetAllByFlakeId'](arg1);
}

export function GetAllByRange(arg1, arg2) {
  return window['go']['todos']['TodosService']['GetAllByRange'](arg1, arg2);
}

export function Remove(arg1) {
  return window['go']['todos']['TodosService']['Remove'](arg1);
}

export function SetDone(arg1) {
  return window['go']['todos']['TodosService']['SetDone'](arg1);
}
