/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as BowlsRouteImport } from './routes/bowls/route'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const BowlsRouteRoute = BowlsRouteImport.update({
  id: '/bowls',
  path: '/bowls',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/bowls': {
      id: '/bowls'
      path: '/bowls'
      fullPath: '/bowls'
      preLoaderRoute: typeof BowlsRouteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bowls': typeof BowlsRouteRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bowls': typeof BowlsRouteRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/bowls': typeof BowlsRouteRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bowls'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bowls'
  id: '__root__' | '/' | '/bowls'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BowlsRouteRoute: typeof BowlsRouteRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BowlsRouteRoute: BowlsRouteRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/bowls"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/bowls": {
      "filePath": "bowls/route.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
