/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as BowlsImport } from './routes/bowls'
import { Route as IndexImport } from './routes/index'
import { Route as BowlsAddImport } from './routes/bowls_.add'
import { Route as BowlsBowlIdImport } from './routes/bowls_.$bowlId'

// Create/Update Routes

const BowlsRoute = BowlsImport.update({
  id: '/bowls',
  path: '/bowls',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const BowlsAddRoute = BowlsAddImport.update({
  id: '/bowls_/add',
  path: '/bowls/add',
  getParentRoute: () => rootRoute,
} as any)

const BowlsBowlIdRoute = BowlsBowlIdImport.update({
  id: '/bowls_/$bowlId',
  path: '/bowls/$bowlId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/bowls': {
      id: '/bowls'
      path: '/bowls'
      fullPath: '/bowls'
      preLoaderRoute: typeof BowlsImport
      parentRoute: typeof rootRoute
    }
    '/bowls_/$bowlId': {
      id: '/bowls_/$bowlId'
      path: '/bowls/$bowlId'
      fullPath: '/bowls/$bowlId'
      preLoaderRoute: typeof BowlsBowlIdImport
      parentRoute: typeof rootRoute
    }
    '/bowls_/add': {
      id: '/bowls_/add'
      path: '/bowls/add'
      fullPath: '/bowls/add'
      preLoaderRoute: typeof BowlsAddImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bowls': typeof BowlsRoute
  '/bowls/$bowlId': typeof BowlsBowlIdRoute
  '/bowls/add': typeof BowlsAddRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bowls': typeof BowlsRoute
  '/bowls/$bowlId': typeof BowlsBowlIdRoute
  '/bowls/add': typeof BowlsAddRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/bowls': typeof BowlsRoute
  '/bowls_/$bowlId': typeof BowlsBowlIdRoute
  '/bowls_/add': typeof BowlsAddRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bowls' | '/bowls/$bowlId' | '/bowls/add'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bowls' | '/bowls/$bowlId' | '/bowls/add'
  id: '__root__' | '/' | '/bowls' | '/bowls_/$bowlId' | '/bowls_/add'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BowlsRoute: typeof BowlsRoute
  BowlsBowlIdRoute: typeof BowlsBowlIdRoute
  BowlsAddRoute: typeof BowlsAddRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BowlsRoute: BowlsRoute,
  BowlsBowlIdRoute: BowlsBowlIdRoute,
  BowlsAddRoute: BowlsAddRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/bowls",
        "/bowls_/$bowlId",
        "/bowls_/add"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/bowls": {
      "filePath": "bowls.tsx"
    },
    "/bowls_/$bowlId": {
      "filePath": "bowls_.$bowlId.tsx"
    },
    "/bowls_/add": {
      "filePath": "bowls_.add.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
